version : '3'

services:
    lb:
        image: haproxy
        ports:
            - "8888:8888"
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    nodeapp1:
        image: mahendrarathore20/nodeapp
        environment:
            - APPID=1111
    nodeapp2:
        image: mahendrarathore20/nodeapp
        environment:
            - APPID=2222
